# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/hello.proto\x12\x05Hello\"*\n\x0cHelloRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x02 \x01(\t2=\n\x05Hello\x12\x34\n\x05Hello\x12\x13.Hello.HelloRequest\x1a\x14.Hello.HelloResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=70
  _globals['_HELLORESPONSE']._serialized_start=72
  _globals['_HELLORESPONSE']._serialized_end=104
  _globals['_HELLO']._serialized_start=106
  _globals['_HELLO']._serialized_end=167
# @@protoc_insertion_point(module_scope)
